version: '3.3'
services:
        nginx:
                image: nginx:latest
                container_name: nginx
                depends_on:
                        - client
                        - service
                        - consumer
                        - mongoretriever
                        - verify
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
                        - target: 443
                          published: 443
                          protocol: tcp
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf 
                        - /etc/letsencrypt/:/etc/letsencrypt/
        jenkins:
                image: bobcrutchley/jenkins:latest
                container_name: jenkins
                ports:
                        - target: 8080
                          published: 8080
                          protocol: tcp
                volumes:
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
        client:
                image: amclient
                container_name: client
                ports:
                        - target: 3000
                          published: 3000
        service:
                ports:
                        - target: 8081
                          published: 8081
                image: amservice
                container_name: service
        consumer:
                ports: 
                        - target: 8084
                          published: 8084
                image: amconsumer
                container_name: consumer
        mongoretriever:
                ports:
                        - target: 8087
                          published: 8087
                image: amretriever
                container_name: retriever
        verify:
                ports:
                        - target: 8088
                          published: 8088
                image: amverify
                container_name: verify
