version: '3.3'
services:
        nginx:
                image: amnginx
                container_name: nginx

                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
        jenkins:
                image: bobcrutchley/jenkins:latest
                container_name: jenkins
                ports:
                        - target: 8080
                          published: 8080
                          protocol: tcp
                volumes:
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
        client:
                image: amclient
                container_name: client
