version: '3.3'
services:
        nginx:
                image: amnginx
                container_name: nginx
                depends_on:
                        - client
                        - service
                        - consumer
                        - mongoretriever
                        - verify
                        - colourgen
                ports:
                        - target: 80
                          published: 80
                          protocol: tcp
                        - target: 443
                          published: 443
                          protocol: tcp
                volumes:
                        - ./nginx.conf:/etc/nginx/nginx.conf 
                        - /etc/letsencrypt/:/etc/letsencrypt/
        jenkins:
                image: bobcrutchley/jenkins:latest
                container_name: jenkins
                ports:
                        - target: 8080
                          published: 8080
                          protocol: tcp
                volumes:
                        - type: bind
                          source: /var/run/docker.sock
                          target: /var/run/docker.sock
        client:
                image: amclient
                container_name: client
                ports:
                        - target: 3000
                          published: 3000
        service:
                image: amservice
                container_name: service
                ports:
                        - target: 8081
                          published: 8081
        consumer:
                image: amconsumer
                container_name: consumer
                ports: 
                        - target: 8084
                          published: 8084
        mongoretriever:
                image: amretriever
                container_name: retriever
                ports:
                        - target: 8087
                          published: 8087
        verify:
                image: amverify
                container_name: verify
                ports:
                        - target: 8088
                          published: 8088
        colourgen:
                image: amcolourgen
                container_name: colourgen                
                ports: 
                        - target: 8083
                          published: 8083
        mongodb: 
                image: mongo:latest
                container_name: mongodb
                ports: 
                        - target: 27017
                          published: 27017
        activemq:
                image: bobcrutchley/activemq
                container_name: activemq
                ports: 
                        - target: 3306
                          published: 3306
